env:
  - GO111MODULE=on
  - GOPROXY=https://goproxy.io

before:
  hooks:
    - sudo apt-get update
    - sudo apt-get install -y gcc-arm-linux-gnueabihf
    - go mod download

builds:
  -
    env:
      - CC=arm-linux-gnueabihf-gcc
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7

archives:
  - files:
    - configs/*

checksum:
  name_template: 'checksums.txt'
